version: 1.0.{build}

image: Visual Studio 2019
environment:
  RUST_VERSION: stable
  matrix:
    - TARGET: x86_64-pc-windows-gnu
      BITS: 64
    - TARGET: i686-pc-windows-msvc
    - TARGET: x86_64-pc-windows-msvc
install:
  - ps: |
      if ($Env:TARGET -eq 'x86_64-pc-windows-gnu') {
          $Env:PATH += ';C:\msys64\mingw64\bin'
      } ElseIf ($Env:TARGET -eq 'i686-pc-windows-gnu') {
          $Env:PATH += ';C:\msys64\mingw32\bin'
      }
      Invoke-WebRequest -Uri "https://win.rustup.rs/" -OutFile "rustup-init.exe"
      & ./rustup-init.exe -y --default-host $Env:TARGET --default-toolchain $Env:RUST_VERSION
      $Env:PATH += ";C:/Users/appveyor/.cargo/bin";
      & rustc -Vv
      & cargo -V

cache: C:\Users\appveyor\.cargo\registry
build_script:
  - ps: |
      & cargo build --target $Env:TARGET --release
      Copy-Item -Force -Recurse etc "./target/$Env:TARGET/release/"
      Copy-Item -Force -Recurse tools "./target/$Env:TARGET/release/"
      cd "./target/$Env:TARGET/release/"
      mkdir bin
      Copy-Item -Force wxwork_robotd.exe bin/
      if ( Test-Path "$Env:TARGET.zip" ) { Remove-Item -Force "$Env:TARGET.zip" }
      Compress-Archive -DestinationPath "$Env:TARGET.zip" -Path etc,bin,tools
      Get-ChildItem
      Get-ChildItem -Recurse etc,bin,tools
      Copy-Item -Force "$Env:TARGET.zip" ../../../
      cd ../../../

artifacts:
  - path: "*.zip"
    name: release-package

deploy:
  - provider: GitHub
    auth_token:
      secure: pXYJRg9JiTwAA+dSOgtvNDsgRd9dRDHx9LTOT4c4kRWMSEMtOJri1BMfPNuEDxYv
    artifact: release-package
    force_update: true
    draft: true
    on:
      APPVEYOR_REPO_TAG: true
